### ISSUE TITLE
server_state vs state – broken RFC compliance?

### ISSUE THREAD

**Issue by ap** [ritou/p5-oauth-lite2#9]
[RFC 6749](https://tools.ietf.org/html/rfc6749) does not contain any mention of a `server_state` parameter. It only mentions `state`. It seems like OAuth::Lite2 and OIDC::Lite use `server_state` wherever the RFC demands `state`? I think that means the modules do not conform to the RFC?

**Comment by ritou** [comment]
Sorry for the late reply.

server_state is an original feature and is not standardized. Existing states are created by the Client, but they may be guessable strings or fixed values. server_state can be made more secure than a normal state by having the Server pay out the state value.

However, it's optional and you can ignore it if you don't want to use it.
